### ISSUE TITLE
스터디 방향 개선안

### ISSUE THREAD

**Issue by kwan7595** [MinboyKim/BojAlgorithmStudy#131]
현재 문제풀이 양상을 보면, 스트릭 유지를 위해 풀기만 한다는 판단을 했음. 판단 근거는 다음과 같음.
 1. PR내용 부실. 코드리뷰 진행이 버겁다.
 2. Notion에 comment 부분 부실. 
---
 이거 양치기만 하다가 알고리즘 체화 못할 것 같아서, 다음과 같이 스터디 방향을 바꿀 것을 제안한다.
1. 매일매일 문제풀이는 계속 진행 (오문추 및 개인별 추가 문풀 동일)
2. Notion에 문제 핵심 풀이 반드시 comment로 남길 것. 서로 확인하고 질문 댓글로 남기기.
3.  1주일에 한번씩 온라인 또는 오프라인으로 만나서, 그 주에 풀었던 문제 중 가장 인상 깊었던 문제 3개를 골라 각자 설명하기. 기록해서 노션에 주차별 알고리즘 정리 글 올리기.
다른 개선 방향이 있으면 댓글로 의논해 보는 걸로.

**Comment by eogns47** [comment]
아니면 코드를짤때 주석을 꼼꼼히 달면 pr후 코드리뷰에 도움이 될것 같습니다 (+ 협업 연습)

**Comment by MinboyKim** [comment]
우선은 주석이랑 pr, 노션에 좀 더 열심히 쓰는걸로 하고 저 계절학기 끝나면 그때부터 관희형이 말한대로 해보는거 어떨까 싶네요

**Comment by kwan7595** [comment]
그럼 주석 다는 방향으로 하고, 동민이 계절 끝나면 다시 회의해보도록 하죠
